### ISSUE TITLE
How to build 8.x-custom kernel myself?

### ISSUE THREAD

**Issue by foreverything** [ahmedradaideh/OnePlus3T#1]
Hey ahmedradaideh
Can you tell me how to build 8.x-custom, I run "make" in bash but it back with a error.
Is this need some dependences or command option ?

**Comment by mostafa-z** [comment]
hi
it may helps you out :)
https://forum.xda-developers.com/android/software-hacking/reference-how-to-compile-android-kernel-t3627297

**Comment by foreverything** [comment]
Thanks! I will try.

**Comment by ahmedradaideh** [comment]
Any problem, please tell me. Enjoy.
